### PR TITLE
add day 38 content

### PR DESCRIPTION
**Pull request by januaryofmine**

### CODE REVIEW

**Comment by januaryofmine** [comment]
@nartc 
Thank you for your reviews. I will research about Ivy way of LazyLoad and update as soon as possible.

**Comment by januaryofmine** [comment]
Hi @nartc,
I have already update content using Lazy Load for dynamic components and remove entryComponents. Please kindly review it.
Thank you.

**Comment by januaryofmine** [comment]
Hi @nartc,
I saw in plan in day 36 is about Angular Reactive Form, do I need change day of this?

**Comment by nartc** [comment]
cc @tieppt regards to his question about day 36 content. 

@januaryofmine Let's wait for Tiep's answer

**Comment by tieppt** [comment]
@januaryofmine em có thể để vào Day 38

**Comment by nartc** [comment]
@januaryofmine can you also update README to link to your post?

**Comment by nartc** [comment]
Thanks for the PR

**Pull request merged**
